# The point of this file is to run commands which should ideally be run outside work hours, without the need of being in place ourselves
# Disable the cron once done.

name: Run AKS command on prod

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 17 10 6' #Set specific yearly date in https://crontab.guru/

jobs:
  run-aks-command:
    name: Job
    runs-on: ubuntu-latest
    steps:
      - name: 'Set env variables'
        run: |
          echo "AZCLIVERSION=2.12.1" >> $GITHUB_ENV
      - name: 'az login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Run az aks commands'
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            az extension add --upgrade -n aks-preview
            az aks nodepool upgrade --resource-group sdpaks-prod --cluster-name sdpaks-prod-k8s --node-image-only