# ARM template validate and apply. Should be synced and triggered on changes to the arm-template folder 
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  push:
    branches:
      - master
      - arm-testing
      - nor
    paths:
    - 'arm-templates/*'
    - 'arm-templates/*/*'
    - '.github/workflows/*'

env:
  LOCATION: 'norwayeast' 
  FILE1: 'https://raw.githubusercontent.com/equinor/sdp-aks/${GITHUB_REF##*/}/arm-templates/base/deploy-arm.json'
  PARAM1: 'https://raw.githubusercontent.com/equinor/sdp-aks/${GITHUB_REF##*/}/arm-templates/${GITHUB_REF##*/}/deploy-arm.parameters.json'
  REF: ${GITHUB_REF##*/}
  REF2: ${GITHUB_REF}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        # Paste output of `az ad sp create-for-rbac --name Apply-ARMTemplate --role "Contributor" --sdk-auth` as value of secret variable: AZURE_CREDENTIALS, add to Repo settings --> secrets
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
          echo ${{ env.REF }}
          echo ${{ env.REF2 }}
          echo ${GITHUB_REF##*/}
          az deployment validate --location ${{ env.LOCATION }} --template-uri https://raw.githubusercontent.com/equinor/sdp-aks/${{ env.REF }}/arm-templates/base/deploy-arm.json  --parameters https://raw.githubusercontent.com/equinor/sdp-aks/${{ env.REF }}/arm-templates/${{ env.REF }}/deploy-arm.parameters.json
          az deployment create --location ${{ env.LOCATION }} --template-uri https://raw.githubusercontent.com/equinor/sdp-aks/${{ env.REF }}/arm-templates/base  --parameters  https://raw.githubusercontent.com/equinor/sdp-aks/${{ env.REF }}/arm-templates/${{ env.REF }}/deploy-arm.parameters.json