# ARM template validate and apply. Should be synced and triggered on changes to the arm-template folder 
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  push:
    branches:
      - master
  schedule:
  - cron: "20  * * *"

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '10.x'                # set this to the node version to use
  AZURE_CREDENTIALS: ''

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Azure Login
      uses: Azure/login@v1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}

        
      # Validate, then deploy ARM templates
    - name: Azure CLI script to validate
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az deployment validate --location norwayeast --template-file {template-file} --debug
          az deployment create --location norwayeast
