# ARM template validate and apply. Should be synced and triggered on changes to the arm-template folder
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
name: 'Apply ARM template'
on:
  push:
    branches:
      - prod
      - dev
    paths:
    - 'arm-templates/**'
    - '.github/workflows/Apply-ARMTemplates.yml'
  pull_request:
    branches:
      - prod
      - dev
    paths:
    - 'arm-templates/**'
    - '.github/workflows/Apply-ARMTemplates.yml'

env:
  LOCATION: 'norwayeast'
  AKS: 'https://raw.githubusercontent.com/equinor/sdp-aks/${GITHUB_REF##*/}/arm-templates/base/deploy-arm.json'
  AKS_PARAMS: 'https://raw.githubusercontent.com/equinor/sdp-aks/${GITHUB_REF##*/}/arm-templates/${GITHUB_REF##*/}/deploy-arm.parameters.json'
  CLASSIC_SUB: 'S066-SDP-Tools-Classic'
  CLASSIC_EXTERNAL: 'https://raw.githubusercontent.com/equinor/sdp-aks/${GITHUB_REF##*/}/arm-templates/classic/deploy-externalvms.json'
  EXTERNAL_GROUP: 'sdp-external-vms'
  INTERNAL_GROUP: 'sdp-internal-vms'
  CLASSIC_INTERNAL: 'https://raw.githubusercontent.com/equinor/sdp-aks/${GITHUB_REF##*/}/arm-templates/classic/deploy-internalvms.json'
  CLASSIC_PARAMS: 'https://raw.githubusercontent.com/equinor/sdp-aks/${GITHUB_REF##*/}/arm-templates/classic-values/deploy-vms.parameters.json'
  AZCLIVERSION: '2.5.1'
jobs:
  # AKS deployments are made on a subscription scope
  deploy-aks-arm:
    name: Apply AKS ARM template
    runs-on: ubuntu-latest
    steps:
      - name: 'az login'
        uses: azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac --name Apply-ARMTemplate --role "Contributor" --sdk-auth` as value of secret variable: AZURE_CREDENTIALS, add to Repo settings --> secrets
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'az AKS deployment what-if'
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            az deployment sub what-if --location ${{ env.LOCATION }} --template-uri ${{ env.AKS }}  --parameters ${{ env.AKS_PARAMS }} > /dev/null
      - name: 'az  AKS deployment create'
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            az deployment sub create --location ${{ env.LOCATION }} --template-uri ${{ env.AKS }}  --parameters ${{ env.AKS_PARAMS }}
            echo Succcessfully updated - ${GITHUB_REF##*/} cluster

  # Classic deployments are made on a group scope
  deploy-classic-external-arm:
    name: Apply Classic External ARM template
    runs-on: ubuntu-latest
    steps:
      - name: 'az login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'az CLASSIC_EXTERNAL deployment what-if'
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            az deployment group what-if --subscription ${{ env.CLASSIC_SUB }} --resource-group ${{ env.EXTERNAL_GROUP }} --template-uri ${{ env.CLASSIC_EXTERNAL }}  --parameters ${{ env.CLASSIC_PARAMS }} > /dev/null
      - name: 'az CLASSIC_EXTERNAL deployment create'
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            az deployment group create --subscription ${{ env.CLASSIC_SUB }} --resource-group ${{ env.EXTERNAL_GROUP }} --template-uri ${{ env.CLASSIC_EXTERNAL }}  --parameters ${{ env.CLASSIC_PARAMS }}

  deploy-classic-internal-arm:
    name: Apply Classic Internal ARM template
    runs-on: ubuntu-latest
    steps:
      - name: 'az login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'az CLASSIC_INTERNAL deployment what-if'
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            az deployment group what-if --subscription ${{ env.CLASSIC_SUB }} --resource-group ${{ env.INTERNAL_GROUP }} --template-uri ${{ env.CLASSIC_INTERNAL }}  --parameters ${{ env.CLASSIC_PARAMS }} > /dev/null
      - name: 'az CLASSIC_INTERNAL deployment create'
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            az deployment group create --subscription ${{ env.CLASSIC_SUB }} --resource-group ${{ env.INTERNAL_GROUP }} --template-uri ${{ env.CLASSIC_INTERNAL }}  --parameters ${{ env.CLASSIC_PARAMS }}
