# ARM template validate and apply. Should be synced and triggered on changes to the arm-template folder 
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  push:
    branches:
      - master
      - develop
      - nor
    paths:
    - 'arm-templates/*'

env:
  LOCATION: 'norwayeast' 
  FILE1: 'https://github.com/equinor/sdp-aks/tree/${GITHUB_REF##*/}/arm-templates/base'
  PARAM1: 'https://raw.githubusercontent.com/equinor/sdp-aks/${GITHUB_REF##*/}/arm-templates/${GITHUB_REF##*/}/deploy-arm.parameters.json'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Azure Login
      uses: Azure/login@v1
      with:
        # Paste output of `az ad sp create-for-rbac --scopes /subscriptions/<subId>/resourceGroups/<rgName1> /subscriptions/<subId>/resourceGroups/<rgNameN> --name Apply-ARMTemplate --role "Contributor"` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}

        
    # Validate, then deploy ARM templates
    - name: Azure CLI script to validate
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az deployment validate --location ${{ env.LOCATION }} --template-uri ${{ env.FILE1 }}  --parameters ${{ env.PARAM1 }} --debug
          az deployment create --location ${{ env.LOCATION }} --template-uri ${{ env.FILE1 }} --parameters  ${{ env.PARAM1 }}
