# ARM template validate and apply. Should be synced and triggered on changes to the arm-template folder
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
name: 'Apply Omnia classic ARM templates'
on:
  workflow_dispatch:
  push:
    branches:
      - prod
      - dev
    paths:
    - 'arm-templates/classic/*'
    - 'arm-templates/classic-values/*'

env:
  CLASSIC_EXTERNAL: 'https://raw.githubusercontent.com/equinor/sdp-omnia/${GITHUB_REF##*/}/arm-templates/classic/deploy-externalvms.json'
  CLASSIC_INTERNAL: 'https://raw.githubusercontent.com/equinor/sdp-omnia/${GITHUB_REF##*/}/arm-templates/classic/deploy-internalvms.json'
  CLASSIC_PARAMS: 'https://raw.githubusercontent.com/equinor/sdp-omnia/${GITHUB_REF##*/}/arm-templates/classic-values/deploy-vms.parameters.json'
jobs:
  # Classic deployments are made on a group scope
  deploy-classic-external-arm:
    name: Apply Classic External ARM template
    runs-on: ubuntu-latest
    steps:
      - name: 'Set env variables'
        run: |
          echo "norwayeast" >> "${LOCATION}"
          echo "S066-SDP-Tools-Classic" >> "${CLASSIC_SUB"}
          echo "sdp-external-vms" >> "${EXTERNAL_GROUP "}
          echo "sdp-internal-vms" >> "${INTERNAL_GROUP"}
          echo "2.12.1" >> "${AZCLIVERSION"}
          echo "https://raw.githubusercontent.com/equinor/sdp-omnia/${GITHUB_REF##*/}/arm-templates/classic/deploy-externalvms.json" >> "${CLASSIC_EXTERNAL"}
          echo "https://raw.githubusercontent.com/equinor/sdp-omnia/${GITHUB_REF##*/}/arm-templates/classic/deploy-internalvms.json" >> "${CLASSIC_INTERNAL"}
          echo "https://raw.githubusercontent.com/equinor/sdp-omnia/${GITHUB_REF##*/}/arm-templates/classic-values/deploy-vms.parameters.json" >> "${CLASSIC_PARAMS"}
      - name: 'az login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'az CLASSIC_EXTERNAL deployment what-if'
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            az deployment group what-if --subscription ${{ env.CLASSIC_SUB }} --resource-group ${{ env.EXTERNAL_GROUP }} --template-uri ${{ env.CLASSIC_EXTERNAL }}  --parameters ${{ env.CLASSIC_PARAMS }} > /dev/null
     
      - name: 'az CLASSIC_EXTERNAL deployment create'
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            az deployment group create --subscription ${{ env.CLASSIC_SUB }} --resource-group ${{ env.EXTERNAL_GROUP }} --template-uri ${{ env.CLASSIC_EXTERNAL }}  --parameters ${{ env.CLASSIC_PARAMS }}

  deploy-classic-internal-arm:
    name: Apply Classic Internal ARM template
    runs-on: ubuntu-latest
    steps:
      - name: 'az login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'az CLASSIC_INTERNAL deployment what-if'
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            az deployment group what-if --subscription ${{ env.CLASSIC_SUB }} --resource-group ${{ env.INTERNAL_GROUP }} --template-uri ${{ env.CLASSIC_INTERNAL }}  --parameters ${{ env.CLASSIC_PARAMS }} > /dev/null
      
      - name: 'az CLASSIC_INTERNAL deployment create'
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            az deployment group create --subscription ${{ env.CLASSIC_SUB }} --resource-group ${{ env.INTERNAL_GROUP }} --template-uri ${{ env.CLASSIC_INTERNAL }}  --parameters ${{ env.CLASSIC_PARAMS }}
